# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48ce84d372907fff6638c93997c552f86b107575d312f241606886c6a531ccc2af021955ed8de2c138a9a1af78634d3c2e3fb3270eef5bbd0b92bf29b37174f1

test:
  secret_key_base: f41f5a284ba26a902a649a6257cf707580e9f26aadc32cda9b2e33944e3b7e987a2833d340b5932265b82b5b44d754d8ff0d546cb10805590af55aed5060c867

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
